box_finder_node:
  ros__parameters:
    max_pass_filter_fm: 0.40
    voxel_grid_size_fm: 0.01
    min_cluster_size_fm: 30

    max_pass_filter_global: 0.7
    voxel_grid_size_global: 0.01
    plane_distance_threshold_global: 0.01
    min_cluster_size_global: 200

    min_averaging_tries: 3
    averaging_tries: 5